### ISSUE TITLE
Testing a checklist

### ISSUE THREAD

**Issue by grovduck** [grovduck/web2#1]
- [x] a task list item
- [x] list syntax required
- [ ] normal **formatting**, @mentions, #1234 refs
- [ ] incomplete
- [x] completed
